---
- name: 'Copy mongodb repo'
  copy:
    src: ../templates/mongodb-org-3.4.repo
    dest: /etc/yum.repos.d/mongodb-org-3.4.repo

- name: 'Install mongodb-org'
  package:
    name: mongodb-org
    state: latest
