---
name: 'Install mongodb'
debug:
  msg: 'Install if not installed yet'

name: 'Create database'
debug:
  msg: 'Create if not created yet'

name: 'Update demo runs count'
debug:
  msg: 'Increase demo runs count'

name: 'Update total number of users having executed demo'
debug:
  msg: 'Search username for duplicates if found don't increase if not found increase'

name: 'Update number of runs per user'
debug:
  msg: 'Maybe can be merged with the step above'
