---
- name: 'Install mongodb'
  debug:
    msg: 'Install if not installed yet'

- name: 'Update demo runs count'
  command: "./update_db.py update_runs_count mongodb://{{ mongodb_username }}:{{ mongodb_password }}@{{ mongodb_url }}:{{ mongodb_port }}/{{ mongodb_db_name }}"
  args:
    chdir: '{{ role_path }}/files'

- name: 'Update number of runs per user'
  command: "./update_db.py update_count_per_user mongodb://{{ mongodb_username }}:{{ mongodb_password }}@{{ mongodb_url }}:{{ mongodb_port }}/{{ mongodb_db_name }} {{ labs_username }}"
  args:
    chdir: '{{ role_path }}/files'
